# Generated by Django 3.1.4 on 2021-01-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210104_0002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
    ]
