# Generated by Django 3.1.4 on 2021-01-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210104_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest_index',
            field=models.FloatField(default=0),
        ),
    ]
