# Generated by Django 3.1.4 on 2021-01-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210106_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotInterestWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
            ],
        ),
    ]
