# Generated by Django 3.1.4 on 2021-01-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_interestword_notinterestword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotInterestWord',
            new_name='NegativeWord',
        ),
        migrations.RenameModel(
            old_name='InterestWord',
            new_name='PositiveWord',
        ),
    ]
