# Generated by Django 3.1.4 on 2021-01-10 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='article',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='articles.article',
                unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='article',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='articles.article',
                unique=True),
        ),
    ]
